# Gaming workspace routing
assign [class="$class_bottles"] $ws9
assign [class="$class_citra"] $ws9
assign [class="$class_dolphin_emu"] $ws9
assign [class="$class_heroic"] $ws9
assign [class="$class_pcsx2"] $ws9
assign [class="$class_rpcs3"] $ws9
assign [class="$class_steam_app"] $ws9
assign [class="$class_steam"] $ws9
assign [class="$class_vita3k"] $ws9
assign [class="$class_yuzu"] $ws9
