# Kitty windows
for_window [class="$class_kitty"] floating enable, resize set 50 ppt 50 ppt, move position center
for_window [class="$class_kitty" title="$title_task_manager"] floating enable, move position center
