# Messaging
for_window [class="$class_signal"] move container to workspace current, floating enable, resize set 50 ppt 70 ppt, move position mouse
for_window [class="$class_telegram"] move container to workspace current, floating enable, resize set 50 ppt 70 ppt, move position mouse
