# Miscellaneous floating applications
for_window [class="$class_1password"] floating enable
for_window [class="$class_avd"] floating enable
for_window [class="$class_blueman_manager"] floating enable
for_window [class="$class_haguichi"] floating enable
for_window [class="$class_nitrogen"] floating enable
for_window [class="$class_obs"] floating enable
for_window [class="$class_protonvpn"] floating enable
for_window [class="$class_qt6ct"] floating enable
for_window [class="$class_wpg"] floating enable
for_window [class="$class_yad"] floating enable
