# Miscellaneous floating applications
for_window [class="$class_blueman_manager"] floating enable
for_window [class="$class_haguichi"] floating enable
for_window [class="$class_nm_applet"] floating enable
for_window [class="$class_obs"] floating enable
for_window [class="$class_wpg"] floating enable
for_window [class="^easyterm.py$"] floating enable
