# Polkit
exec --no-startup-id /usr/bin/lxqt-policykit-agent

# Keyring
exec --no-startup-id gnome-keyring-daemon --start --components=pkcs11,secrets,ssh

# XDG Portal
exec --no-startup-id /usr/lib/xdg-desktop-portal -r
exec --no-startup-id /usr/lib/xdg-desktop-portal-gtk -r
