# 󰊴 gaming
assign [class="^bottles$"] $ws9
assign [class="^Citra$"] $ws9
assign [class="^heroic$"] $ws9
assign [class="^pcsx2$"] $ws9
assign [class="^RPCS3$"] $ws9
assign [class="^steam_app"] $ws9
assign [class="^steam$"] $ws9
assign [class="^Vita3K$"] $ws9
assign [class="^yuzu$"] $ws9
