# Action menu [mode]
mode "$actions" {
    bindsym 1 exec --no-startup-id sh -c 'i3-msg reload >/dev/null && notify-send "i3 config reloaded."', mode "default"
    bindsym 2 exec systemctl reboot, mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

set $actions Actions: [1] Reload i3 config, [2] Reboot

bindsym $mod+r mode "$actions"
