# IM launcher [mode]
set $mode_im Messages: [S]ignal, [T]elegram, [W]hatsapp

mode "$mode_im" {
    bindsym s workspace $ws5; exec --no-startup-id $app_signal, mode "default"
    bindsym t workspace $ws5; exec --no-startup-id $app_telegram, mode "default"
    bindsym w workspace $ws1; exec --no-startup-id xdg-open "https://web.whatsapp.com/", mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+m mode "$mode_im"
