# IM launcher [mode]
set $mode_launch_im Messages: [S]ignal, [T]elegram

mode "$mode_launch_im" {
    bindsym s exec --no-startup-id $app_signal, mode "default"
    bindsym t exec --no-startup-id $app_telegram, mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+m mode "$mode_launch_im"
