# Power menu [mode]
set $mode_power_menu System: [L]ogout, [R]eboot, [S]hutdown

mode "$mode_power_menu" {
    bindsym i exec --no-startup-id loginctl lock-session, mode "default"
    bindsym l exec i3-msg exit, mode "default"
    bindsym r exec systemctl reboot, mode "default"
    bindsym s exec systemctl poweroff -i, mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym Pause mode "$mode_power_menu"
