# Reload menu [mode]
set $mode_reload Reload: [i]3, pi[c]om, Poly[b]ar, Du[n]st, [w]al

mode "$mode_reload" {
    bindsym i exec --no-startup-id sh -c 'i3-msg reload >/dev/null && notify-send "i3 config reloaded."', mode "default"
    bindsym c exec --no-startup-id sh -c 'pkill -USR1 picom && notify-send "Picom reloaded."', mode "default"
    bindsym b exec --no-startup-id sh -c 'polybar-msg cmd restart >/dev/null && notify-send "Polybar reloaded."', mode "default"
    bindsym w exec --no-startup-id sh -c 'wal -R >/dev/null && notify-send "Wal reapplied."', mode "default"
    bindsym n exec --no-startup-id sh -c 'pkill dunst && notify-send "Dunst reloaded."', mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+r mode "$mode_reload"
