# Work launcher [mode]
set $mode_work Work: [1]Password, [C]ode, [D]Beaver, [O]bsidian, [P]ostman, [S]lack

mode "$mode_work" {
    bindsym 1 exec --no-startup-id $app_1password, mode "default"
    bindsym c workspace $ws3; exec --no-startup-id $app_ide, mode "default"
    bindsym d workspace $ws4; exec --no-startup-id $app_dbeaver, mode "default"
    bindsym o workspace $ws7; exec --no-startup-id $app_notes, mode "default"
    bindsym p workspace $ws4; exec --no-startup-id $app_postman, mode "default"
    bindsym s exec --no-startup-id $app_slack, mode "default"

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+w mode "$mode_work"
