[Application]
AllowResizingRectSelection=false
ApplicationStyle=kvantum-dark
AutoCopyToClipboardNewCaptures=true
AutoHideTabs=true
AutoResizeToContent=false
RememberLastSaveDirectory=true
SaveDirectory=/home/codeslicer/Pictures/screenshots/2026
SaveFilename=$Y-$M-$D-$T
SavePosition=false
UseTrayIcon=false

[ImageGrabber]
CaptureCursor=false
LastRectArea=@Rect(0 0 3840 1756)
ShowMainWindowAfterTakingScreenshotEnabled=true

[KImageAnnotator]
AnnotatorDockWidgetsState=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\xb4\0\0\x3\xc1\xfc\x2\0\0\0\x4\xfb\0\0\0\x1c\0T\0o\0o\0l\0 \0S\0\x65\0l\0\x65\0\x63\0t\0i\0o\0n\x1\0\0\0\0\0\0\x1\x30\0\0\0g\0\xff\xff\xff\xfb\0\0\0\x1c\0I\0m\0\x61\0g\0\x65\0 \0S\0\x65\0t\0t\0i\0n\0g\0s\x1\0\0\x1\x37\0\0\0q\0\0\0'\0\xff\xff\xff\xfb\0\0\0\x1a\0I\0t\0\x65\0m\0 \0S\0\x65\0t\0t\0i\0n\0g\0s\x1\0\0\x1\xaf\0\0\x1\x80\0\0\0\x82\0\xff\xff\xff\xfb\0\0\0 \0G\0\x65\0n\0\x65\0r\0\x61\0l\0 \0S\0\x65\0t\0t\0i\0n\0g\0s\x1\0\0\x3\x36\0\0\0\x8b\0\0\0/\0\xff\xff\xff\0\0\x6\xab\0\0\x3\xc1\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)
ToolColor_8=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)
ToolFillType_13=2
ToolFillType_8=0
ToolFont_0=@Variant(\0\0\0@\0\0\0\x14\0S\0\x61\0n\0s\0 \0S\0\x65\0r\0i\0\x66@\"\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0\x32\x10)
ToolFont_1=@Variant(\0\0\0@\0\0\0\x14\0S\0\x61\0n\0s\0 \0S\0\x65\0r\0i\0\x66@.\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
ToolFont_10=@Variant(\0\0\0@\0\0\0\x14\0S\0\x61\0n\0s\0 \0S\0\x65\0r\0i\0\x66@4\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
ToolFont_13=@Variant(\0\0\0@\0\0\0\x14\0S\0\x61\0n\0s\0 \0S\0\x65\0r\0i\0\x66@&\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
ToolFont_6=@Variant(\0\0\0@\0\0\0\x14\0S\0\x61\0n\0s\0 \0S\0\x65\0r\0i\0\x66@.\0\0\0\0\0\0\xff\xff\xff\xff\x5\x1\0K\x10)
ToolObfuscateFactor_0=1
ToolShadowEnabled_13=false
ToolShadowEnabled_8=false
ToolTextColor_13=@Variant(\0\0\0\x43\x1\xff\xff\xff\xff\0\0\0\0\0\0)
ToolType=6
ToolWidth_0=1
ToolWidth_6=1
ToolWidth_8=2

[MainWindow]
Position=@Point(7 7)

[recentImagesPath]
1\imagePath=/home/codeslicer/Pictures/screenshots/2026/2026-06-28-015558.png
10\imagePath=/home/codeslicer/Pictures/screenshots/2026/2026-07-17-113725.png
2\imagePath=/home/codeslicer/Pictures/screenshots/2026/2026-06-28-015603.png
3\imagePath=/home/codeslicer/Pictures/screenshots/2026/2026-06-29-141352.png
4\imagePath=/home/codeslicer/Downloads/3-tag-assistant.png
5\imagePath=/home/codeslicer/Downloads/3-tag-assistant-events.png
6\imagePath=/home/codeslicer/Downloads/6-plp-events.png
7\imagePath=/home/codeslicer/Downloads/2026-07-13-220619.png
8\imagePath=/home/codeslicer/Downloads/2026-07-13-221608.png
9\imagePath=/home/codeslicer/Downloads/2026-07-17-113725.png
size=10
