# Launchers and utility bindings
bindsym $mod+a exec "rofi -modi drun -show drun"
bindsym $mod+e exec $fileManager
bindsym $mod+comma exec code ~/.dotfiles

bindsym Ctrl+Shift+Escape exec --no-startup-id ~/.config/i3/scripts/btop.sh
bindsym $mod+v exec --no-startup-id pavucontrol-qt
bindsym $mod+$alt+n workspace $ws7; exec --no-startup-id flatpak run com.logseq.Logseq
bindsym $mod+o workspace $ws7; exec --no-startup-id ~/AppImages/obsidian.appimage
