# Launchers and utility bindings

## System
bindsym $mod+Return exec --no-startup-id $app_terminal_emulator
bindsym $mod+Escape exec --no-startup-id ~/.config/i3/scripts/btop.sh

## Utils
bindsym $mod+a exec --no-startup-id "rofi -modi drun -show drun"
bindsym $mod+b exec --no-startup-id $app_browser
bindsym $mod+e exec --no-startup-id $app_file_manager
bindsym $mod+p exec --no-startup-id $app_ide ~/.dotfiles
bindsym $mod+v exec --no-startup-id pavucontrol-qt

## Apps
bindsym $mod+c workspace $ws3; exec --no-startup-id $app_ide
bindsym $mod+n workspace $ws7; exec --no-startup-id $app_notes
