# Core window manager bindings
bindsym $alt+F4 kill

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+F11 fullscreen toggle
bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+f floating toggle
bindsym $alt+Tab focus mode_toggle

bindsym $mod+equal scratchpad show
bindsym $mod+minus move scratchpad
bindsym $mod+Tab workspace back_and_forth
