# Screenshot

## Copy
bindsym Print exec --no-startup-id ksnip --rectarea # select area
bindsym Ctrl+Print exec --no-startup-id ksnip --active # focused window
bindsym $mod+Print exec --no-startup-id ksnip --fullscreen # fullscreen

## Save
bindsym Shift+Print exec --no-startup-id ksnip --rectarea --save # select area
bindsym Shift+Ctrl+Print exec --no-startup-id ksnip --active --save # focused window
bindsym Shift+$mod+Print exec --no-startup-id ksnip --fullscreen --save # fullscreen
