# Screenshot
bindsym Print exec --no-startup-id ksnip --rectarea
bindsym Ctrl+Print exec --no-startup-id ksnip --rectarea --save
bindsym Alt+Print exec --no-startup-id ksnip --fullscreen
bindsym Ctrl+Alt+Print exec --no-startup-id ksnip --fullscreen --save
