# Screenshot
bindsym Print exec --no-startup-id ksnip --rectarea
bindsym Ctrl+Print exec --no-startup-id ksnip --rectarea
bindsym Shift+Print exec --no-startup-id ksnip --fullscreen
bindsym $alt+Print exec --no-startup-id ksnip --active
