set $app_1password /opt/1Password/1password
set $app_browser brave
set $app_dbeaver dbeaver
set $app_file_manager thunar
set $app_ide code
set $app_notes flatpak run md.obsidian.Obsidian
set $app_postman flatpak run com.getpostman.Postman
set $app_signal signal-desktop
set $app_slack xdg-open "https://ironplane.slack.com/"
set $app_telegram Telegram
set $app_terminal_emulator kitty
set $app_whatsapp $app_browser --app-id=hnpfjngllnobngcgfapefoaidbinmjnm
