# Shared window matchers
set $class_1password ^1[Pp]assword$
set $class_brave ^[Bb]rave-browser$
set $class_blueman_manager ^[Bb]lueman-manager$
set $class_bottles ^[Bb]ottles$
set $class_code ^[Cc]ode$
set $class_dbeaver ^[Dd][Bb]eaver$
set $class_dolphin_emu ^[Dd]olphin-emu$
set $class_drawio ^(draw\\.io|drawio|[Dd]raw\\.io)$
set $class_firefox ^[Ff]irefox$
set $class_gimp ^[Gg]imp$
set $class_haguichi ^[Hh]aguichi$
set $class_heroic ^[Hh]eroic$
set $class_inkscape ^[Ii]nkscape$
set $class_java ^[Jj]ava$
set $class_btop ^btop$
set $class_kitty ^[Kk]itty$
set $class_ksnip ^[Kk]snip$
set $class_libreoffice ^libreoffice
set $class_meld ^Meld$
set $class_nm_applet ^(nm-applet|Nm-applet|Nm-connection-editor)$
set $class_obs ^[Oo]bs$
set $class_obsidian ^[Oo]bsidian$
set $class_pavucontrol ^[Pp]avucontrol(-qt)?$
set $class_postman ^[Pp]ostman$
set $class_shortwave ^shortwave$
set $class_signal ^[Ss]ignal$
set $class_soffice ^Soffice$
set $class_speedcrunch ^[Ss]peed[Cc]runch$
set $class_steam ^[Ss]team$
set $class_steam_app ^steam_app
set $class_telegram ^([Tt]elegram[Dd]esktop|telegram-desktop)$
set $class_wpg ^Wpg$


set $title_dbeaver ^DBeaver
set $title_firefox_about About Mozilla Firefox
set $title_task_manager ^Task Manager
