set $mod Mod4
set $alt Mod1
set $app_terminal_emulator kitty
set $app_file_manager thunar
set $app_ide code
set $app_notes flatpak run md.obsidian.Obsidian

font pango:Hack Nerd Font Mono 10

floating_modifier $mod
tiling_drag modifier titlebar

set $ws1 "1: www"
set $ws2 "2: files"
set $ws3 "3: dev"
set $ws4 "4: tools"
set $ws5 "5: im"
set $ws6 "6: media"
set $ws7 "7: office"
set $ws8 "8: graphics"
set $ws9 "9: gaming"
set $ws0 "10: system"
