[bar/root]
modules-right = left-separator i3-mode filesystem memory cpu volume-input volume-output datetime systray right-padding

[module/left-separator]
type = custom/text
format-foreground = ${colors.background}

format = 
format-font = 3

[module/i3-mode]
type = internal/i3
format = <label-mode>
format-background = ${colors.background}
format-padding = 0
label-mode-background = ${colors.secondary}
label-mode-padding = 1

[module/filesystem]
type = internal/fs
label-mounted-background = ${colors.background}
format-mounted-prefix-background = ${colors.background}

mount-0 = /
interval = 3600

format-mounted-prefix = 
format-mounted-prefix-font = 4
format-mounted-prefix-padding = 1
format-mounted-prefix-foreground = ${colors.primary}

label-mounted = %percentage_used%%

[module/memory]
type = internal/memory
format-background = ${colors.background}

format-prefix = 
include-file = snippets/icon-prefix.ini

format = <ramp-used>
ramp-used-0 = ▁
ramp-used-0-foreground = ${colors.hardware-usage-0}
ramp-used-1 = ▂
ramp-used-1-foreground = ${colors.hardware-usage-1}
ramp-used-2 = ▃
ramp-used-2-foreground = ${colors.hardware-usage-2}
ramp-used-3 = ▄
ramp-used-3-foreground = ${colors.hardware-usage-3}
ramp-used-4 = ▅
ramp-used-4-foreground = ${colors.hardware-usage-4}
ramp-used-5 = ▆
ramp-used-5-foreground = ${colors.hardware-usage-5}
ramp-used-6 = ▇
ramp-used-6-foreground = ${colors.hardware-usage-6}
ramp-used-7 = █
ramp-used-7-foreground = ${colors.hardware-usage-7}

[module/cpu]
type = internal/cpu
format-background = ${colors.background}

format-prefix = 
include-file = snippets/icon-prefix.ini

format = <ramp-coreload>
ramp-coreload-spacing = 0
ramp-coreload-0 = ▁
ramp-coreload-0-foreground = ${colors.hardware-usage-0}
ramp-coreload-1 = ▂
ramp-coreload-1-foreground = ${colors.hardware-usage-1}
ramp-coreload-2 = ▃
ramp-coreload-2-foreground = ${colors.hardware-usage-2}
ramp-coreload-3 = ▄
ramp-coreload-3-foreground = ${colors.hardware-usage-3}
ramp-coreload-4 = ▅
ramp-coreload-4-foreground = ${colors.hardware-usage-4}
ramp-coreload-5 = ▆
ramp-coreload-5-foreground = ${colors.hardware-usage-5}
ramp-coreload-6 = ▇
ramp-coreload-6-foreground = ${colors.hardware-usage-6}
ramp-coreload-7 = █
ramp-coreload-7-foreground = ${colors.hardware-usage-7}

[module/volume-input]
type = custom/script
label-background = ${colors.background}

# exec = ~/.config/polybar/config.d/scripts/volume-render.sh input
# tail = true

click-right = exec pavucontrol &
click-left = pulseaudio-control --node-type input togmute
click-middle = pulseaudio-control --node-type input --node-blacklist "*.monitor" next-node

scroll-up = pulseaudio-control --node-type input --volume-max 100 --volume-step 5 up
scroll-down = pulseaudio-control --node-type input --volume-max 100 --volume-step 5 down

[module/volume-output]
type = custom/script
label-background = ${colors.background}
# exec = ~/.config/polybar/config.d/scripts/volume-render.sh output
# tail = true

click-right = exec pavucontrol &
click-left = pulseaudio-control togmute
click-middle = pulseaudio-control next-node

scroll-up = pulseaudio-control --volume-max 100 --volume-step 5 up
scroll-down = pulseaudio-control --volume-max 100 --volume-step 5 down

[module/datetime]
type = internal/date
format-background = ${colors.background}

format-prefix = " "

time = 
time-alt = 

date = %H:%M
date-alt = %m/%d/%Y

label = "%{T4}%time%%{T-} %{F#fff}%date%%{F-}"
label-foreground = ${colors.primary}

[module/systray]
type = internal/tray
format-background = ${colors.background}
tray-background = ${colors.background}

tray-spacing = 10

format-prefix = 
include-file = snippets/icon-prefix.ini

[module/right-padding]
type = custom/text
format-background = ${colors.background}
format = " "
